# -*- coding: utf-8 -*-
"""Currency.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xm1D5VzQptWCJFxi6BRyNnzWgnKdqj7z
"""

import requests
from datetime import date
from bs4 import BeautifulSoup
import gspread
from oauth2client.service_account import ServiceAccountCredentials
 
 
CREDENTIALS_FILE = 'currecncy-44bbb26fa938.json'  # Имя файла с закрытым ключом, вы должны подставить свое
scopes = [
    'https://www.googleapis.com/auth/spreadsheets',
    'https://www.googleapis.com/auth/drive'
]
# Читаем ключи из файла
credentials = ServiceAccountCredentials.from_json_keyfile_name(CREDENTIALS_FILE, scopes=scopes)
 
gc = gspread.authorize(credentials)
 
worksheet = gc.open("Currency").sheet1
 
response = requests.get('https://finance.i.ua/')
soup = BeautifulSoup(response.text, 'lxml') # Parse the HTML as a string    
table = soup.find_all('table')[0]
 
templ = []
row_marker = 0
for row in table.find_all('tr'):
    selector1 = soup.select_one('thead')
    selector1.decompose()
    ths = row.find_all('th')
    for th in ths:
        templ.append(th.get_text())
    column_marker = 0
    columns = row.find_all('td')
    row_marker += 1
    for column in columns:
        selector2 = soup.select_one('._description')
        selector2.decompose()
        templ.append(column.get_text())
        column_marker += 1
 
try:
    cell = worksheet.find("NEXT")
    row_next = cell.row - 2
except:
    row_next = 0
 
date_now = date.today().strftime("%d.%m.%Y")
row_len = 0
marker = 1 + row_next
for each_row in range(row_marker):
    marker += 1
    cell_list = worksheet.range('A{0}:E{0}'.format(marker))
    cell_values = [date_now]+templ[row_len:row_len+4]
    for i, val in enumerate(cell_values):  #gives us a tuple of an index and value
        cell_list[i].value = val    #use the index on cell_list and the val from cell_values
    worksheet.update_cells(cell_list)
    row_len += 4
worksheet.update_cell(marker , 1, 'NEXT')